name: CICD automation

on:
  push:
    branches: [ "main" ]
    
jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        ls
        mvn package --file pom.xml

 
  depchecktest:
    runs-on: ubuntu-latest
    needs: compile
    
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Project-Document'
          path: '.'
          format: 'HTML'
          out: 'reports.json' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired

  security-scan:
    runs-on: ubuntu-latest
    needs: depchecktest
    
    - uses: actions/checkout@v4
    - name: Installation Trivy
      run: |
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y

    - name: Trivy-FS-scan
      run: trivy fs --format table -o fs.report.json .


    - name: Gitleaks-installation
      run: sudo apt install gitleaks -y

    - name: Gitleaks scan
      run: gitleaks detect --source . -r gitleaks-report -f json
      
    
